---
local_archive_path: /tmp
jails_zfs_pool: tank
jails_dir: /jails
jails_version: 10.1
jails_clone_interface: lo1
jails_ipv4_range: 192.168.199.1-30/27
jails_ipv4_net: 192.168.199.0/27
jail_master_tpl_name: master
jail_master_tpl_addr: 192.168.199.1
jails_domain_name: jails.example.com

jails_admin_pass: vagrant
jails_admin_user: vagrant
jails_admin_key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"

jails:
  testjail:
    ip4: 192.168.199.2
    ip6: "::2"
  testail2:
    ip4: 192.168.199.3
    ip6: "::3"
